name: vue
version: 0.2.0
author: Emil Persson <emil.n.persson@gmail.com>
description: An interface for interacting with a JavaScript instance of Vue.js
homepage: http://github.com/emilniklas/vue-dart
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  reflectable: ^0.3.4
  js: ^0.6.0
dev_dependencies:
  test: any